# Generated by Django 4.0.6 on 2025-02-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_paymentconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
