# Generated by Django 4.0.6 on 2025-02-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code_required', models.BooleanField(default=True)),
                ('imf_code_required', models.BooleanField(default=True)),
                ('otp_required', models.BooleanField(default=True)),
                ('anti_terrorist_code_required', models.BooleanField(default=True)),
                ('anti_money_laundering_code_required', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
