# Generated by Django 4.0.6 on 2025-02-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('bank', 'Bank Account'), ('usdt', 'USDT')], max_length=20, unique=True)),
                ('account_number', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('additional_info', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
